[package]
name = "chains"
version = "0.1.0"
edition = "2021"
authors = ["DaniPopes <danipopes1@proton.me>"]
license = "MIT"
readme = "README.md"

[dependencies]
once_cell = "1.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
